### ISSUE TITLE
python wheel releases

### ISSUE THREAD

**Issue by shreyanshmohnot** [mdolab/pyoptsparse#11]
When can we get python wheel package for pyoptsparse to configure it with openmdao? Trying to install pyoptsparse in Anaconda Windows but unable to compile the whole package. It would be great to see wheel package available for this.
Thanks

**Comment by nwu63** [comment]
Sorry for not responding to this earlier. I'm not really familiar with how Python packaging works, but my understanding is that this will take some work/resources on our end, especially since pyOptSparse contains both Fortran and C code that requires compilation. We also do not plan to support OS other than Linux due to the complexities involved with compiling/wrapping code in these environments. The only thing on our roadmap at the moment is potentially publishing on pyPI but again I'm not really sure how much effort would be required to do that.
