### ISSUE TITLE
Documentation for fail flags

### ISSUE THREAD

**Issue by andrewtrainor** [mdolab/pyoptsparse#136]
## Type of issue
What types of issue is it?
- Documentation update

## Description
I am currently working on bench-marking different solvers in multiple frameworks. I need to get my solution to return if it was successful or not. I have looked around the OpenMDAO website and the docs that are contained specifically for pyoptsparse but I have been unable to get it to return a boolean. Is there more detailed documentation on how to get it to return this? I have tried variations of sol.Flag, sol.status, etc.. but have been unsuccessful. any help or resources would be greatly appreciated.

thanks!

**Comment by nwu63** [comment]
Just to clarify, are you asking about the return status from the optimizer, regarding whether the optimization succeeded? This is called "inform" in pyOptSparse terminology, and it will not be a boolean -- an optimizer may exit due to many different circumstances. For each optimizer, there is a table in the pyOptSparse documentation detailing what the exit codes mean. The value can be accessed with `sol.optInform`.

Now you mention OpenMDAO, are you using the pyOptSparse driver there, or running pyOptSparse on its own? With OpenMDAO I don't know how the informs get passed to them, you'll have to ask the developers there.

**Comment by andrewtrainor** [comment]
That is correct, I am trying to get if the optimization succeeded. I am using the pyoptsparse on its own, not the driver. That is very helpful because most of the frameworks that I have dealt with return a boolean. I will look at the exit codes in the documentation. Thanks!

**Comment by andrewtrainor** [comment]
Which folder is the exit code documentation in?

**Comment by nwu63** [comment]
We host our documentation on readthedocs. See for example [here](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/optimizers/pyslsqp.html) for SLSQP.

**Comment by andrewtrainor** [comment]
that is very helpful, thank you.
