### ISSUE TITLE
Missing informs value for PyPSQP 

### ISSUE THREAD

**Issue by hschilling** [mdolab/pyoptsparse#146]
## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Bugfix (non-breaking change which fixes an issue)

## Description
The wrapper for PSQP defines mappings from return values to strings

```
self.informs = {
--
1: "Change in design variable was less than or equal to tolerance",
2: "Change in objective function was less than or equal to tolerance",
3: "Objective function less than or equal to tolerance",
4: "Maximum constraint value is less than or equal to tolerance",
11: "Maximum number of iterations exceeded",
12: "Maximum number of function evaluations exceeded",
13: "Maximum number of gradient evaluations exceeded",
-6: "Termination criterion not satisfied, but obtained point is acceptable",
}

```

But PSQP can have a return code of -10

```
     IF (IREST.GT.0) THEN
         CALL MXDSMI(N,H)
         LD = MIN(LD,1)
         IDECF = 1
         IF (KIT.LT.NIT) THEN
             NRES = NRES + 1
             KIT = NIT
         ELSE
             ITERM = -10
             IF (ITERS.LT.0) ITERM = ITERS - 5
             GO TO 80
         END IF
     END IF
```

So I get exceptions for that case. 

```
  File “/home/travis/miniconda/envs/PY3.8/lib/python3.8/site-packages/pyoptsparse/pyPSQP/pyPSQP.py”, line 261, in __call__
    sol_inform[“text”] = self.informs[inform]
KeyError: -10
```
I would submit a PR but I don't know what text to use to describe this termination condition.

**Comment by nwu63** [comment]
After looking through the PSQP source code, I see that the `ITERM` is defined [here](https://github.com/mdolab/pyoptsparse/blob/fe6e515b70fec714e9c320317745aa6fe6c133f7/pyoptsparse/pyPSQP/source/psqp_wrap.f90#L46) and I guess when this was first implemented, someone overlooked the line `ITERM<0-IF THE METHOD FAILED.`

We'll fix this soon-ish, but it's not a priority for us at the moment. Alternatively, feel free to submit a PR if you feel like you can fix this yourself. From what I can see, it just involves two things:
1. add a new entry to the `self.informs` dictionary, say with the key `-1`.
2. add a check to catch all negative informs except for `-6` and map that to the `-1` key when returning the actual inform.

**Comment by hschilling** [comment]
A couple days I think is fine. As I mention in the updated Issue text, I really don't feel confident that I could write a correct description of the -10 termination condition. Thanks!

**Comment by sseraj** [comment]
@hschilling It looks like what causes a -10 code is running an optimization as a restart when the case has not been run before. Is this consistent with what you were running?

**Comment by hschilling** [comment]
I was wondering that too when I saw where -10 was set in the Fortran code. 

We got the error from running this OpenMDAO test. There is nothing there that makes me think this should be a restart. It's just build a model and run. 

Thanks for looking into this. I can help debug if you want. Just let me know what you want me to try.

```
    def test_initial_run_PSQP(self):
        _, local_opt = set_pyoptsparse_opt('PSQP')
        if local_opt != 'PSQP':
            raise unittest.SkipTest("pyoptsparse is not providing PSQP")

        # Make sure all our opts have run the initial point just once.
        prob = om.Problem()
        model = prob.model
        model.add_subsystem('p1', om.IndepVarComp('x', val=1.0))
        comp = model.add_subsystem('comp1', DataSave())
        model.connect('p1.x', 'comp1.x')

        model.add_design_var('p1.x', lower=-100.0, upper=100.0)
        model.add_objective('comp1.y')
        model.add_constraint('p1.x', lower=-200.0)

        prob.driver = pyOptSparseDriver()
        prob.driver.options['print_results'] = False
        prob.driver.options['optimizer'] = 'PSQP'
        prob.driver.opt_settings['IPRINT'] = 0

        prob.setup()
        prob.run_driver()

        self.assertEqual(comp.visited_points[0], 1.0)
        self.assertNotEqual(comp.visited_points[1], 1.0)

```

**Comment by sseraj** [comment]
I misinterpreted what 'restart' means here. It actually refers to resetting the Hessian to the identity matrix. `ITERM<0` means there were two consecutive restarts because something went wrong with the algorithm (usually in the line search), so `THE METHOD FAILED` seems appropriate (although vague).

We can add better descriptions for exit codes -7 and -8 based on the line search termination indicators ([`ITERS`](https://github.com/mdolab/pyoptsparse/blob/fe6e515b70fec714e9c320317745aa6fe6c133f7/pyoptsparse/pyPSQP/source/pqsubs.f#L2681-L2687)) and the line `IF (ITERS.LT.0) ITERM = ITERS - 5`. How to get -10 is not so clear, but I think it's possible if the directional derivative for the line search is positive immediately after a restart (based on [this](https://github.com/mdolab/pyoptsparse/blob/fe6e515b70fec714e9c320317745aa6fe6c133f7/pyoptsparse/pyPSQP/source/psqp.f#L485-L499)). I'm hesitant to add that though since it's not stated in the source code.

**Comment by hschilling** [comment]
Thanks for looking into this. So what is the plan ahead? What is odd is that we have had this OpenMDAO test for quite a while. It is part of our current release and master. I was just updating OpenMDAO so that it could support your recently re-added ParOpt and now this test is failing.

**Comment by nwu63** [comment]
I think we just have to do what we can with the information available. If you have a good idea of what -7 and -8 indicates, then those can be added to the informs directly. We would then have another inform which you can set the key to say -10, and redirect other negative informs to that, since it seems that a variety of negative informs are possible. The message will be vague but that's not really something for us to deal with, since the PSQP code comments/documentation is rather lacking. Does that make sense?

**Comment by sseraj** [comment]
Before #138, the informs for PSQP were commented out. I will update the informs as @nwu63 suggested which should solve the problem.

**Comment by hschilling** [comment]
Thanks @nwu63 and @sseraj . Sounds like a good solution to me. Thanks
