### ISSUE TITLE
Replace string option for solver with constant or type

### ISSUE THREAD

**Issue by matbesancon** [mdolab/pyoptsparse#169]
In the solver definition
opt = OPT(opt_name, options), having a string with the name of the solver is error-prone (a typo in the solver name) and hard to discover. Furthermore, it makes the integration of other solvers hard since a list of string names has to be maintained in sync with the solvers.
Passing a solver object (for example from a solvers module) could make things easier on the user.

Issue written for the JOSS review https://github.com/openjournals/joss-reviews/issues/2564

**Comment by nwu63** [comment]
It's currently possible to instantiate a solver object without using strings, for example `slsqp = SLSQP(optOptions=optOptions)` instead of `OPT('slsqp', optOptions=optOptions)`. As you said, we maintain a list of strings and map them to the optimizer [here](https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyOpt_optimizer.py#L890), and I agree that this is not very elegant. Would it be sufficient to update the documentation/examples to recommend this approach instead of using strings?

**Comment by nwu63** [comment]
Actually, I took a look at the code and I've reversed my stance. I think it's useful to be able to import a single object, i.e. `OPT` and change the optimizer on-the-fly. If I want to swap between two optimizers, it's much better to instantiate with `OPT(optimizer)` instead of wrapping everything in conditionals, essentially duplicating the code that is already [in pyOptSparse](https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyOpt_optimizer.py#L890). That would unnecessarily clutter every runscript.

**Comment by matbesancon** [comment]
> Would it be sufficient to update the documentation/examples to recommend this approach instead of using strings?

in my opinion yes

**Comment by nwu63** [comment]
Sorry Mathieu, not sure if you saw the comment above. I think there's value in being able to do this via strings since it allows you to quickly swap optimization algorithms. We also cast all the strings to lower case to try and reduce the possibility of typos.

**Comment by dhill2522** [comment]
Just an end user perspective, but could using an enum work well here? I think you could dodge the possibility of typos, while still allowing easily swappable optimizers.

I am thinking something along the lines of `opt = OPT(optimizers.IPOPT, optOptions=optOptions` where `optimizers` would be an enum defined in a module somewhere.

**Comment by nwu63** [comment]
Oh yeah that's a good idea. The capitalization of some optimizers is always tricky, for example `ParOpt` vs. `PAROPT`, but nevertheless I think this could work well. I'll play around with this and report back.

**Comment by dhill2522** [comment]
Sounds good. I can see that with the capitalization. Depending on the editor in use it may actually become easier as fancier editors will autocomplete enum values, but not strings.

**Comment by matbesancon** [comment]
> I think there's value in being able to do this via strings since it allows you to quickly swap optimization algorithms

yes I agree that it should remain an option. I raised this issue to wonder if it should be the principal way recommended in the documentation (included the quick start)
