### ISSUE TITLE
Dependence on baseclasses repo

### ISSUE THREAD

**Issue by gjkennedy** [mdolab/pyoptsparse#213]
## Description

The dependencies of pyOptSparse now include the mdolab repo BaseClasses. This causes warning messages when you're missing parts of the MDOLab tool kit such as pygeo. I get:

"Warning: unable to find pygeo module, some functionality in pyWeight_problem will be unavailable"

I don't see why baseclasses adds value to pyOptSparse.

### Steps to reproduce issue

1. Run any script that includes pySNOPT without installing pygeo.

### Current behavior

Described above.

### Expected behavior

No warning messages unrelated to pyOptSparse.

**Comment by nwu63** [comment]
The main reason for including `baseclasses` is that it reduces code duplication for things such as options/type checking, and utility functions that otherwise would have to be defined in several places within the MACH framework.

That being said, I can definitely patch up `baseclasses` to not print those messages -- that's definitely an oversight on our part, and something leftover from _very_ old code. Other than the warning messages, are there any other issues with including `baseclasses` as a dependency?

**Comment by gjkennedy** [comment]
I haven't seen any more issues at this point.

Is pyOptSparse really a part of MACH?

**Comment by nwu63** [comment]
> Is pyOptSparse really a part of MACH?

It's probably the most standalone component but yes it is, see for example [this description](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/machFramework/MACH-Aero.html). As a side note, we now publish `baseclasses` on PyPI so you can install it directly via `pip`, or if you are installing `pyoptsparse` with `pip` it should automatically fetch and install `baseclasses` for you.

**Comment by JustinSGray** [comment]
FWIW I see both sides of this issue. Its good to avoid code duplication, but code coupling is also undesirable. 

pyoptsparse is a pretty generic library. I would say it makes sense for MACH to depend on it, but not the other way around. 

From what I can see, the dependency is on CaseInsensitiveSet. IIRC, I was the one who first added the CaseInsensitiveDict pyoptsparse (or at least I was sitting next to Sandy who did it at my suggestion). So this issue is partly my fault. 

I understand the argument that since its available on pypi and setup.py is handling it then its not that big of a deal to have the dependency. It does avoid a bit of duplication. 

On the other hand, aside from the excellent code documentation/commenting, we're talking about [10 LOC here. ](https://github.com/mdolab/baseclasses/blob/master/baseclasses/utils.py#L112-L151). I think my recommendation would be to avoid the dependency. I find it hard to justify a dependency for 10 LOC. 

Since Im not the one maintaining this anymore, I don't feel that strongly about this. But my recommendation here is not to call pyoptsparse part of MACH. I think that over-specializes it a bit (at least it could appear to) which might scare away some users. If its not part of MACH, it probably shouldn't have MACH dependencies.

**Comment by JustinSGray** [comment]
after a closer look at the repo, I see the underlying motivation for making BaseClasses a dependency. Since it is just pure python, and since they have taken care to publish it on pypi... i retract my objection.

**Comment by nwu63** [comment]
Just to expand a bit on this, the dependence is on the `BaseSolver` class which handles options/type checking, and this is the same piece of code which is used in other packages ranging from ADflow to pyHyp to pytacs. The patch has been merged and is now released as v1.5.1, which can be installed via `pip install -U mdolab-baseclasses`.

**Comment by marcomangano** [comment]
Hello @gjkennedy , do the latest updates fully address the issue with the spurious warning messages?

To follow up on @nwu63 comments, we included `baseclasses` among the dependencies only after we published the package on pyPI, so to ensure a seamless transition to external users. Alongside the `CaseInsensitiveSet` dependency highlighted by @JustinSGray , the most relevant change is that now the `Optimizer` class (and thus `pySNOPT`, `pyIPOPT`, etc...) is now a derived classes of `BaseSolver` - you can check [this PR](https://github.com/mdolab/pyoptsparse/pull/193) for more details. We did this to minimize code duplication and facilitate the repo maintenance. `pyOptSparse` is definitely the most "stand-alone" tool from MDO Lab, but it is still part of MACH and in this cases leverages on the shared code base.

Let us know if we missed any other bugs or issues in this transition!

**Comment by gjkennedy** [comment]
The updates do address the spurious warning messages.
