### ISSUE TITLE
How dose the function "_waitloop"  work in pySNOPT.py?

### ISSUE THREAD

**Issue by qwefhajk** [mdolab/pyoptsparse#263]
I try to figure out how dose the snopt run under MPI and I trace back the _waitloop function in [pySNOPT.py](https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pySNOPT/pySNOPT.py#L486). In the [optimizer.py](https://github.com/mdolab/pyoptsparse/blob/a959ac9038d4d9b7596d0b2845a2bb1b2ec12e79/pyoptsparse/pyOpt_optimizer.py#L669), a "while" loop is set but I don't understand how the parameter "mode" can be turned into -1 and breaks down the loop. Can someone gives me some clue please?

**Comment by marcomangano** [comment]
Hi @qwefhajk, I am not very familiar with the underlying MPI machinery but I can try and explain what's going on at a high level.

Regardless of the number of procs you are using for the optimization calling `mpirun -np <nprocs> <yourscript>.py`, SNOPT only runs on the `root=0` processor. All the other processors are placed in this `_waitloop` function, as you pointed out. The procs available in the MPI environment are then only called at function/gradient evaluation time directly from your runscripts (take a look at [this tutorial](https://mdolab-mach-aero.readthedocs-hosted.com/en/latest/machAeroTutorials/opt_overview.html) to see how we set up the scripts and the functions that are passed to pyOptSparse). When SNOPT is done with the optimization, [the root proc mode changes and it's broadcasted to all the other processors](https://github.com/mdolab/pyoptsparse/blob/a959ac9038d4d9b7596d0b2845a2bb1b2ec12e79/pyoptsparse/pySNOPT/pySNOPT.py#L458-L459), which can now be released from the loop so that the `mpirun` job can be exited successfully.

I see how this is a bit convoluted when you first approach the code, but it is the way pyOptSparse enables the parallelization of the analysis solvers without having to "parallelize" the optimizer as well.

On the side, feel free to ask for more clarifications, but I would close this issue and continue the conversation in the discussion section (we can link the closed issue from there).
