### ISSUE TITLE
Potential Windows Support Solution

### ISSUE THREAD

**Issue by jackm97** [mdolab/pyoptsparse#273]
# Background
I've managed to get pyoptsparse to compile on Windows using mingw and tweaking generated c files. I used conda to help with the process but I'm sure it's possible without conda.

Steps:

1.  Install ipopt and mpi4py using conda
2. Set environment variables for IPOPT support: `set IPOPT_LIB=C:\...\miniconda3\envs\build-env\Library\bin` and `set IPOPT_INC=C:\...\miniconda3\envs\build-env\Library\include\coin-or`.
3. Install [mingw64](https://www.mingw-w64.org/)
4. Run `python setup.py build --compiler=mingw32`. It will compile with errors
5. Edit the C-files in `build\src.win-arch-3.9\pyoptsparse` that have `#include <setjmp.h>` and modified them to `#include <setjmpex.h>`. The relevant files are under the folders for the SLSQP, PSQP and CONMIN optimizers.
6. Rerun `python setup.py build --compiler=mingw32` and this time it should compile with no errors

# Feature Request: Conda Recipe
Is there an easy way to automate this with a conda build recipe? I can help if someone could point me to the current recipes used for the osx and linux packages on conda-forge. I think the setjmp issue may also be a bug with f2py and will be filing a bug report over there as well.

**Comment by nwu63** [comment]
Hey, thanks for writing down the steps. Do all the tests pass?

Regarding the feature request, I'm sure it's possible to put together a conda recipe for this since it's designed for exactly this purpose. However, since we don't use Windows there is little benefit for us to support an additional platform. So I think it's unlikely for us to support Windows and add it to the build matrix for conda-forge. I think this issue will go a long way for others who want to get pyoptsparse working on Windows, and I will add a note in our documentation to point users to this issue.

**Comment by jackm97** [comment]
Testing discussion moved to [PR #274](https://github.com/mdolab/pyoptsparse/pull/274)
