### ISSUE TITLE
Numpy disutils deprecation

### ISSUE THREAD

**Issue by jackm97** [mdolab/pyoptsparse#294]
A little while back I submitted an issue for getting Windows to work and it's working out quite well. I was never able to follow up with the bug report for the parallel file access issues I was running into, and I still hope to give proper info on those errors at some point, but I only use Windows sparingly and haven't yet been able to formulate a proper report. I basically only make sure the Windows build works from time to time since I have Windows users that rely on it.

That said, it isn't the point of this issue but is somewhat related. A little background. You may recall that one of the steps for building on Windows involved editing the auto generated C source code from f2py before rerunning the build command. I was able to hunt down the problematic code in f2py and was going to look into submitting a fix to the numpy project but to my surprise numpy distutils and I believe f2py is [deprecated](https://numpy.org/devdocs/reference/distutils_status_migration.html#distutils-status-migration). It seems the two main recommendations are to either use meson or cmake. 

Does the pyoptsparse team have any plan for this change? Is there any plan to have a more cross-platform build method so others can package it for their platforms more easily? I am very reliant on this software so I'm more than willing to help with that transition as I can. I'm currently looking through the code and doing some digging on the new scipy meson workflow. Would you all be open to proposed solutions to this deprecation?

**Comment by eli-schwartz** [comment]
f2py isn't deprecated AFAIK, just numpy.distutils. The reason for the distutils deprecation is because it is too error-prone to extend setuptools (and various valuable missing features cannot be reasonably added to setuptools at all, such as parallel compilation).

f2py isn't tied to distutils and doesn't have this issue. In fact, the flagship conversion of numpy.distutils to Meson, being carried out in the SciPy repository, makes a lot of use of f2py from inside Meson.

**Comment by nwu63** [comment]
Hey! Yes @eli-schwartz is correct, `f2py` will continue to be maintained although it is in low-maintenance mode AFAIK. I was aware that `numpy.distutils` is being deprecated and have indeed considered switching to either `cmake` or `meson`. There are some things to consider beyond pyOptSparse for this decision, since it ties into the rest of MDO Lab codes and the wider ecosystem, but I am somewhat confident that the new build system would be one of the two mentioned.

There isn't a timeline in place for this yet---I'm graduating this year so I cannot divert too much of my time on this, but I think maybe we can aim for the summer or fall. We're more than happy for others to propose solutions, and my plan was to eventually try both options and see which one we like more. I personally lean more towards meson too but there are other things to consider---new dependencies for end users, building on HPC, adoption by other MDO Lab codes (we try to keep the build process somewhat consistent and we have a large number of repositories), etc. If you want to throw together a `meson` implementation or something that'd be great.

**Comment by eli-schwartz** [comment]
AFAIK there should be no issue using Meson on HPC, especially since that is most likely just some variant of Linux. OS support might be a better topic to consider either way.

As far as dependencies go, Meson is a pretty easy dependency -- you already depend on python, and Meson is a pure python package <1mb.

**Comment by jackm97** [comment]
@eli-schwartz and @nwu63 thanks for the info. I understand this isn't highest priority but I'll take a stab at the meson build if/when I can!
