### ISSUE TITLE
Function of `fail` variable returned by cost function?

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#32]
Good day,

I am using pyOptSparse in an application where the cost function cannot be evaluated successfully for some design variables, so I would like to use the `fail` variable returned to pyOptSparse to let the optimizer know to avoid those areas.

However, when I implement this it seems like pyOptSparse exits immediately when it encounters one of these points, and SNOPT gives the exit status:

```
SNOPTC EXIT  60 -- undefined user-supplied functions
SNOPTC INFO  61 -- undefined function at the first feasible point
```

I'm slightly confused by this, because in the following toy problem, it seems like the value of `fail` has no influence on the outcome of the problem and I get the same result whether `fail=False` or `fail=True`.

```
import pyoptsparse

def objfunc(xdict):

    x = xdict['xvars']
    funcs = {}

    funcs['obj'] = -x[0] * x[1] * x[2]

    funcs['con1'] = x[0] + 2. * x[1] + 2. * x[2] - 72.0
    funcs['con2'] = -x[0] - 2. * x[1] - 2. * x[2]

    fail = False
    return funcs, fail

# Optimization Object
opt_prob = pyoptsparse.Optimization('TP37 Constrained Problem', objfunc)

# Design Variables
x0 = [10, 10, 10]
low = [0, 0, 0]
up = [42, 42, 42]

opt_prob.addVarGroup('xvars', 3, lower=low, upper=up, value=x0)

opt_prob.addCon('con1', upper=0)
opt_prob.addCon('con2', upper=0)

opt_prob.addObj('obj')

# print(opt_prob)

slsqp = pyoptsparse.SLSQP()
# slsqp = pyoptsparse.SNOPT()

sol = slsqp(opt_prob, sens='FD', storeHistory='snopt.hist')
```

Thanks in advance
Michael

**Comment by nwu63** [comment]
Hi Michael,

As you have seen, the optimization will usually struggle if the analysis failed for some reason, as the optimizer doesn't have any information on why it failed, or which regions to avoid. You may find situations where the optimizer repeatedly steps into undefined regions, stalling the optimization. In general, it's better to avoid introducing undefined regions to gradient-based optimization, and instead try to adjust design variable bounds, use alternative parameterization, or introduce additional constraints to try and circumvent the issue.

In this specific case, the error code is quite useful, as it indicates that one of the initial points was undefined. If SNOPT encounters these issues later in the optimization (indicated by INFO 63), then it will try to take 1/10 the step size and try again, but if it occurs early then it basically gives up. One thing you can try is to start from a different point which is hopefully further away from undefined regions. Or, if some progress was made before hitting this point, you can try to reduce the major step size limit, so that it takes smaller steps. Again, the optimizer has no ways of knowing which regions are undefined, so it's best to address this from a problem-setup perspective. If it's obvious to you that the optimum is far away from these undefined regions, then by adjusting the `penalty parameter`, `major step limit` and appropriate scaling, you should prevent the optimizer from entering these regions. The SNOPT manual has descriptions of the corresponding settings.

Hope this helps and best of luck!

**Comment by michK** [comment]
Thank you very much, that is very useful information.

Kindest regards
Michael
