### ISSUE TITLE
SLSQP Does not compile in the latest version.

### ISSUE THREAD

**Issue by NAnand-TUD** [mdolab/pyoptsparse#324]
## Description

SLSQP does not compile when following the documentation. I believe something is missing. 

### Steps to reproduce issue

1. I used pip3 install . on the pyoptsparse folder after cloning the latest version of the code.
2. Also by uninstalling with pip and by reinstalling the SLSQP is not compiled (this is recommended in the documentation)
3. However, in v2.0 this works like a charm.

**Comment by marcomangano** [comment]
Hello Nitish,
What OS and compilers are you using?  What error message are you getting? Please make sure that you are also using a recent version of Numpy (1.19 or 1.21 are currently tested). The build process changed substantially since v2.0 so with this little information it is hard to guess what's the problem

**Comment by NAnand-TUD** [comment]
Thanks for your response, Marco! I followed build_pyoptsparse and finally sorted the installation. Thanks for your quick response anyway. 

Cheers!
