### ISSUE TITLE
Missing pySNOPT information code for timeout

### ISSUE THREAD

**Issue by cfrontin** [mdolab/pyoptsparse#332]
## Description

When running SNOPT through `pySNOPT`, using the `Time limit` SNOPT option, `pyoptsparse`/`pySNOPT` fails with a key error if the time limit is reached, because [the code for timeout is not handled in `pySNOPT`](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySNOPT/pySNOPT.py#L137).

### Steps to reproduce issue

Run any SNOPT optimization with arg `options= {"Time limit": 20}`.

### Current behavior

`KeyError: 34`

### Expected behavior

Return result, showing [informational code #34 from p. 42 of the SNOPT manual](http://www.sbsi-sol-optimize.com/manuals/SNOPT%20Manual.pdf).

### Suggested fix:

Insert
```
            34: "time limit reached",
```
at [pySNOPT.py, line 137](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySNOPT/pySNOPT.py#L137)

**Comment by marcomangano** [comment]
Hello @cfrontin,
thanks for catching this missing `informs` key. We will open a PR shortly to make sure that the key list is consistent with SNOPT 7.7. Apparently the `time limit` option was introduced after SNOPT 7.2 and we haven't updated that dictionary since.

Once that option is available, it should become the recommended approach to set a time limit for SNOPT optimizations.
As an alternative approach, you can pass a `timeLimit` option to the `optimizer` object in the runscript - see [this section of the documentation](https://mdolab-pyoptsparse.readthedocs-hosted.com/en/latest/advancedFeatures.html#time-limit-for-snopt-only).

**Comment by cfrontin** [comment]
thanks, @marcomangano!
